name: "resnet50_trt"
platform: "tensorrt_plan"
max_batch_size: 256
input [
{
    name: "input"
    data_type:TYPE_FP32
    dims:[3, -1, -1]
    
}
]
output[
{
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1000 ]
    label_filename: "labels.txt"
}
]
